import "./styles/globals.css"
import { BlitzProvider } from "./blitz-client"
import { Inter } from "next/font/google"
import getCurrentUser from "./users/queries/getCurrentUser"
import { invoke } from "./blitz-server"
import Nav from "./components/Nav"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: { title: "New Blitz App", template: "%s – Blitz" },
  description: "Generated by blitz new ",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const currentUser = await invoke(getCurrentUser, null)
  return (
    <html lang="en">
      <body>
        <BlitzProvider>
          <>
            <main>
              <Nav currentUser={currentUser} />
              {children}
            </main>
          </>
        </BlitzProvider>
      </body>
    </html>
  )
}
